CodeCareer/Areas/User/ViewModels/AlienProfileViewModel.cs
namespace CodeCareer.Areas.User.ViewModels
{
    public class AlienProfileViewModel
    {
        public string CurrentUserEmail { get; set; }
        public string AlienUserEmail { get; set; }

        public bool WantsToSubscribe { get; set; } = false;
    }
}

CodeCareer/Areas/User/ViewModels/CreatePublicationViewModel.cs
using CodeCareer.Areas.User.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;

namespace CodeCareer.Areas.User.ViewModels
{
    public class CreatePublicationViewModel
    {
        [BindNever]
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        [Required(ErrorMessage = "Введите описание")]
        [MaxLength(1000, ErrorMessage = "Максимальная длина - 1000 символов")]
        public string Content { get; set; }
    }
}

CodeCareer/Areas/User/ViewModels/PublicationFeedViewModel.cs
using CodeCareer.Areas.User.Models;
using Humanizer;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace CodeCareer.Areas.User.ViewModels
{
    public class PublicationFeedViewModel
    {
        public string CurrentUserEmail {  get; set; }
        public string PublicationUserEmail { get; set; }

        public bool WantsToSubscribe { get; set; } = false;


        //public bool WantsToBoostRating { get; set; } = false;

        public List<string> TagNames { get; set; } = new List<string>();


        public string SortType { get; set; } = "нет";

        public PublicationFeedViewModel()
        {

        }
        public PublicationFeedViewModel(string currentUserEmail)
        {
            CurrentUserEmail = currentUserEmail;
        }
    }
}

CodeCareer/Areas/Admin/Controllers/HomeController.cs
using CodeCareer.Areas.Admin.Models;
using CodeCareer.Areas.User.Models;
using CodeCareer.Areas.User.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CodeCareer.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("{area}/{action}")]
    public class HomeController : Controller
    {
        public static AdminModel admin = new AdminModel();

        private readonly ITagService _tagService;

        public HomeController(ITagService tagService)
        {
            _tagService = tagService;
        }

        public IActionResult Index()
        {
            if (!admin.IsAuthorizate)
            {
                return RedirectToAction("Authorization");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Authorization()
        {
            ViewBag.WrongPassword = string.Empty;
            return View(admin);
        }

        [HttpPost]
        public IActionResult Authorization(AdminModel adminP)
        {
            if (adminP.Password == AdminModel.PASSWORD)
            {
                admin = adminP;
                admin.IsAuthorizate = true;
                return RedirectToAction("AuthorizationSuccess");
            }
            else
            {
                ViewBag.WrongPassword = "Неверный пароль!";
                return View(admin);
            }
        }

        public IActionResult AuthorizationSuccess()
        {
            return View();
        }

        public IActionResult LogoutAdmin()
        {
            admin = new AdminModel();
            return View();
        }

        [HttpGet]
        public IActionResult AddTags()
        {
            if (admin.IsAuthorizate)
            {
                return View(new TagModel());
            }
            else
            {
                return RedirectToAction("Authorization");
            }
        }

        [HttpPost]
        public IActionResult AddTags(TagModel tag)
        {
            if (ModelState.IsValid)
            {
                _tagService.AddTagModel(tag);
                return View(new TagModel());
            }
            else
            {
                return View(tag);
            }
        }
    }
}

CodeCareer/Areas/User/Controllers/HomeController.cs
using CodeCareer.Areas.User.Models;
using CodeCareer.Areas.User.Services.Implementations.JsonServices;
using CodeCareer.Areas.User.Services.Interfaces;
using CodeCareer.Areas.User.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CodeCareer.Areas.User.Controllers
{
    [Area("User")]
    public class HomeController : Controller
    {
        public static UserModel currentUser { get; set; } = new UserModel();

        private readonly IUserService _userService;
        private readonly IPublicationService _publicationService;
        private readonly ITagService _tagService;

        public HomeController(IUserService userService, IPublicationService publicationService, ITagService tagService)
        {
            _userService = userService;
            _publicationService = publicationService;
            _tagService = tagService;
        }

        [HttpGet]
        [Route("")]
        [Route("{action}")]
        public ActionResult Index()
        {
            return View(currentUser);
        }

        [HttpGet]
        public IActionResult Authorizate()
        {
            return View(new UserViewModel());
        }

        [HttpPost]
        public IActionResult Authorizate(UserViewModel user)
        {
            if (ModelState.IsValid)
            {

                var dbUser = _userService.GetUserModels().Where(u => u.Email == user.Email).FirstOrDefault();

                

                // Если пользователь не найден в БД
                if (dbUser == null)
                {
                    currentUser.CreateUser(user);
                    _userService.AddUserModel(currentUser);
                    return RedirectToAction("SuccessAuthorizate");
                }
                else
                {
                    if (dbUser.Password == user.Password)
                    {
                        currentUser = dbUser;
                        return RedirectToAction("SuccessAuthorizate");
                    }
                    else
                    {
                        ViewData["isWrongAnswer"] = "true";
                        return View(user);
                    }
                }
            }
            else
            {
                return View(user);
            }
        }
        public IActionResult SuccessAuthorizate()
        {
            return View(currentUser);
        }

        public IActionResult LogoutUser()
        {
            currentUser = new UserModel();
            return View();
        }

        [HttpGet]
        public IActionResult Profile()
        {
            if (currentUser.FullName != null)
            {
                return View(currentUser);
            }
            else
            {
                return RedirectToAction("Authorizate");
            }
        }

        [HttpGet]
        public IActionResult AlienProfile(string userEmail)
        {
            AlienProfileViewModel model = new AlienProfileViewModel()
            {
                CurrentUserEmail = currentUser.Email,
                AlienUserEmail = userEmail
            };
            
            return View(model);
        }

        [HttpPost]
        public IActionResult AlienProfile(AlienProfileViewModel viewModel)
        {
            // если пользователь не зарегистрирован
            if (currentUser.FullName == string.Empty)
            {
                // Ничего не делаем
            }
            else
            {
                UserModel alienUser = _userService.GetUserModels().FirstOrDefault(u => u.Email == viewModel.AlienUserEmail);

                if (alienUser == null)
                {
                    Console.WriteLine($"Null. {viewModel.AlienUserEmail}");
                }

                if (viewModel.WantsToSubscribe)
                {
                    alienUser.SubscribersEmails.Add(currentUser.Email);
                    alienUser.Subscribers += 1;
                    currentUser.Subscriptions += 1;
                    currentUser.SubscriptionsEmails.Add(alienUser.Email);

                    alienUser.Rating += Constants.PlUS_RATING_FOR_SUBSCRIBE;
                    currentUser.Rating += Constants.PlUS_RATING_FOR_SUBSCRIPTION;

                    _userService.UpdateUserModel(alienUser);
                    _userService.UpdateUserModel(currentUser);

                }
                else
                {

                    if (alienUser.SubscribersEmails.Remove(currentUser.Email))
                    {
                        alienUser.Subscribers -= 1;
                        currentUser.Subscriptions -= 1;
                        currentUser.SubscriptionsEmails.Remove(alienUser.Email);

                        alienUser.Rating -= Constants.PlUS_RATING_FOR_SUBSCRIBE;
                        currentUser.Rating -= Constants.PlUS_RATING_FOR_SUBSCRIPTION;
                    }

                    _userService.UpdateUserModel(alienUser);
                    _userService.UpdateUserModel(currentUser);

                }

            }

            AlienProfileViewModel model = new AlienProfileViewModel()
            {
                CurrentUserEmail = currentUser.Email,
                AlienUserEmail = viewModel.AlienUserEmail
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult ShowSubscribes(string userEmail)
        {
            UserModel user = _userService.GetUserModels().FirstOrDefault(u => u.Email == userEmail);
            return View(user);
        }

        [HttpGet]
        public IActionResult ShowSubscriptions(string userEmail)
        {
            UserModel user = _userService.GetUserModels().FirstOrDefault(u => u.Email == userEmail);
            return View(user);
        }

        [HttpGet]
        public IActionResult EditProfile()
        {
            return View(currentUser);
        }

        [HttpPost]
        public IActionResult EditProfile(UserModel user)
        {
            if (user.Info != string.Empty)
            {
                _userService.RemoveUserModel(currentUser);
                currentUser.Info = user.Info;
                currentUser.ShowSubscriptions = user.ShowSubscriptions;
                _userService.AddUserModel(currentUser);

                return RedirectToAction("EditProfileSuccess");
            }
            return View(user);
        }

        public IActionResult EditProfileSuccess()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreatePublication()
        {
            return View(new CreatePublicationViewModel());
        }

        [HttpPost]
        public IActionResult CreatePublication(CreatePublicationViewModel viewModel, List<string> TagNames)
        {

            if (!string.IsNullOrEmpty(viewModel.Content))
            {
                var publication = new PublicationModel { Content = viewModel.Content };

                publication.Tags = _tagService.GetTagModels().Where(t => TagNames.Contains(t.Name)).ToHashSet();

                publication.User = currentUser;
                currentUser.Rating += Constants.PlUS_RATING_FOR_POST;
                _publicationService.AddPublicationModel(publication);

                _userService.UpdateUserModel(currentUser);

                return RedirectToAction("Profile");
            }
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult PublicationFeed()
        {
            return View(new PublicationFeedViewModel(currentUser.Email));
        }

        [HttpPost]
        public IActionResult PublicationFeed(PublicationFeedViewModel viewModel, List<string> SelectedTags)
        {
            // если пользователь не зарегистрирован
            if (viewModel.CurrentUserEmail == null)
            {
                // Ничего не делаем
            }
            else
            {
                UserModel publicationUser = _userService.GetUserModels().FirstOrDefault(u => u.Email == viewModel.PublicationUserEmail);
                if (viewModel.WantsToSubscribe)
                {
                    publicationUser.SubscribersEmails.Add(currentUser.Email);
                    publicationUser.Subscribers += 1;
                    currentUser.Subscriptions += 1;
                    currentUser.SubscriptionsEmails.Add(publicationUser.Email);

                    publicationUser.Rating += Constants.PlUS_RATING_FOR_SUBSCRIBE;
                    currentUser.Rating += Constants.PlUS_RATING_FOR_SUBSCRIPTION;

                    _userService.UpdateUserModel(publicationUser);
                    _userService.UpdateUserModel(currentUser);
                    
                }
                else
                {
                    
                    if (publicationUser.SubscribersEmails.Remove(currentUser.Email))
                    {
                        publicationUser.Subscribers -= 1;
                        currentUser.Subscriptions -= 1;
                        currentUser.SubscriptionsEmails.Remove(publicationUser.Email);

                        publicationUser.Rating -= Constants.PlUS_RATING_FOR_SUBSCRIBE;
                        currentUser.Rating -= Constants.PlUS_RATING_FOR_SUBSCRIPTION;
                    }

                    _userService.UpdateUserModel(publicationUser);
                    _userService.UpdateUserModel(currentUser);

                }
                
            }

            viewModel = new PublicationFeedViewModel
            {
                CurrentUserEmail = currentUser.Email,
                TagNames = SelectedTags,
                SortType = viewModel.SortType,
            };

            return View(viewModel);
        }

        public IActionResult Top100Users()
        {
            var users = _userService.GetUserModels().OrderByDescending(u => u.Rating).Take(100).ToList();
            return View(users);
        }

        [HttpGet]
        public IActionResult AddSkillTags()
        {

CodeCareer/Areas/User/ViewComponents/PublicationViewComponent.cs
using CodeCareer.Areas.User.Models;
using Microsoft.AspNetCore.Mvc;

namespace CodeCareer.Areas.User.ViewComponents
{
    public class PublicationViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(PublicationModel publicationP)
        {
            return View(publicationP);
        }
    }
}

CodeCareer/Areas/User/ViewComponents/TagViewComponent.cs
using CodeCareer.Areas.User.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace CodeCareer.Areas.User.ViewComponents
{
    public class TagViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(TagModel tagP)
        {
            return View(tagP);
        }
    }
}

CodeCareer/Areas/User/Views/Home/AddSkillTags.cshtml
@inject ITagService TagService

@{
	var tags = TagService.GetTagModels();
}

<form asp-area="User" asp-controller="Home" asp-action="AddSkillTags" method="post">
	<h1>Выберите навыки</h1>
	@foreach (var tag in tags)
	{
		if (HomeController.currentUser.SkillTags.Contains(tag))
		{
			<div>
				<input type="checkbox"
					   name="skillTagNames"
					   value="@tag.Name"
					   checked />
				<label>@tag.Name</label>
			</div>
		}
		else
		{
			<div>
				<input type="checkbox"
					   name="skillTagNames"
					   value="@tag.Name" />
				<label>@tag.Name</label>
			</div>
		}
	}
	<button type="submit">Добавить</button>
</form>

CodeCareer/Areas/User/Views/Home/AlienProfile.cshtml
@using CodeCareer.Areas.User.Services.Interfaces
@using CodeCareer.Areas.User.Services.Implementations.JsonServices
@model AlienProfileViewModel

@inject IPublicationService PublicationService
@inject IUserService UserService

@{
	UserModel user = UserService.GetUserModels().FirstOrDefault(u => u.Email == Model.AlienUserEmail);
	ViewBag.Title = $"Профиль {user.FullName}";
	var publications = PublicationService.GetPublicationModels().Where(p => p.User.Email == Model.AlienUserEmail).ToList();
	publications.Reverse();

	var currentUser = UserService.GetUserModels().FirstOrDefault(u => u.Email == Model.CurrentUserEmail);
}

<div>
	<div>
		@*Шапка*@

	</div>
	<h4>@user.FullName - @user.Status</h4>
	<p>@user.Info</p>
	<p><a asp-area="User" asp-controller="Home" asp-action="ShowSubscribes" asp-route-userEmail="@user.Email">@user.Subscribers подписчиков</a></p>
	@if (user.ShowSubscriptions)
	{
		<p><a asp-area="User" asp-controller="Home" asp-action="ShowSubscriptions" asp-route-userEmail="@user.Email">@user.Subscriptions подписок</a></p>
	}
	<p>@user.Rating рейтинга</p>

	@*Кнопка "подписаться"*@
	@if (currentUser != null)
	{
		<form asp-area="Users" asp-controller="Home" asp-action="PublicationFeed" method="post">

			<input asp-for="AlienUserEmail" value="@Model.AlienUserEmail" type="hidden" />
			<input type="hidden" asp-for="WantsToSubscribe" value="@(!currentUser.SubscriptionsEmails.Contains(Model.AlienUserEmail))" />

			@*Если у текущего пользователя нет в подписках создателя публикации, то значение кнопки - подписаться*@
			<button type="submit">@(!currentUser.SubscriptionsEmails.Contains(Model.AlienUserEmail) ? "Подписаться" : "Отписаться")</button>
		</form>
	}
</div>

<div>
	<h4>Навыки</h4>
	@foreach (var tag in user.SkillTags)
	{
		@await Component.InvokeAsync("Tag", new { tagP = tag })
	}
</div>

<div>
	<h2>Публикации</h2>
	@foreach (var publication in publications)
	{
		@await Component.InvokeAsync("Publication", new { publicationP = publication })
	}
</div>

CodeCareer/Areas/User/Views/Home/Authorizate.cshtml
@model UserViewModel
@{
	ViewBag.Title = "Авторизация";
	ViewData["isWrongPassword"] = string.Empty;
}

<h1>Авторизация пользователя</h1>
<form asp-area="User" asp-controller="Home" asp-action="Authorizate" method="post">
	<h3>Имя пользователя:</h3>
	<input asp-for="FullName"/>
	<span asp-validation-for="FullName"></span>

	<h3>Почта:</h3>
	<input type="email" asp-for="Email" />
	<span asp-validation-for="Email"></span>

	<h3>Пароль:</h3>
	<input type="password" asp-for="Password" />
	<span asp-validation-for="Password"></span>
	<br />
	@if (ViewData["isWrongPassword"] != string.Empty)
	{
		<h4>Неверный пароль!</h4>
	}

	<button type="submit">Войти</button>
</form>

CodeCareer/Areas/User/Views/Home/Community.cshtml
<h1>Найдётся всё!</h1>

<br />

<a asp-area="User" asp-controller="Home" asp-action="FindUser">Найти пользователя</a>

<a asp-area="User" asp-controller="Home" asp-action="FindPublication">Найти публикацию</a>

CodeCareer/Areas/User/Views/Home/CreatePublication.cshtml
@model CreatePublicationViewModel
@{
	ViewBag.Title = "Создание публикации";
}

@inject ITagService TagService

@{
	var tags = TagService.GetTagModels();
}


<h1>Создание публикации:</h1>

<form asp-area="User" asp-controller="Home" asp-action="CreatePublication" method="post">

	<textarea asp-for="Content"></textarea>
	<span asp-validation-for="Content"></span>

	<h5>Выберите теги</h5>
	@foreach (var tag in tags)
	{
		<div>
			<input type="checkbox"
				   name="TagNames"
				   value="@tag.Name" />
			<label>@tag.Name</label>
		</div>
	}

	<button type="submit">Создать</button>
</form>

<h4><a asp-area="User" asp-controller="Home" asp-action="Profile">Отменить создание публикации</a></h4>

CodeCareer/Areas/User/Views/Home/EditProfile.cshtml
@using CodeCareer.Areas.User.Services.Interfaces
@using CodeCareer.Areas.User.Services.Implementations.JsonServices
@model UserModel

@inject ITagService TagService

@{
	ViewBag.Title = "Редактировать Профиль";
}

<div>
	<div>
		@*Шапка*@

	</div>
	<form asp-area="User" asp-controller="Home" asp-action="EditProfile" method="post">
		<h4>@Model.FullName - @Model.Status</h4>
		<p>Введите краткую информацию о себе</p>
		<textarea asp-for="Info">@Model.Info</textarea>
		<span asp-validation-for="Info"></span>

		<p>@Model.Subscribers подписчиков</p>
		<p>@Model.Rating рейтинга</p>

		<p>Отображать подписки?</p>
		<select asp-for="ShowSubscriptions"> 
			<option value="@(true)">Да</option>
			<option value="@(false)">Нет</option>
		</select>
		<br />
		<br />

		<button type="submit">Сохранить изменения</button>
	</form>
</div>

<h4><a asp-area="User" asp-controller="Home" asp-action="Profile">Отменить изменения</a></h4>

CodeCareer/Areas/User/Views/Home/EditProfileSuccess.cshtml
@{

}

<h1>Профиль настроен успешно!</h1>
<a asp-area="User" asp-controller="Home" asp-action="Index">На главную</a>

CodeCareer/Areas/User/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Главная";
}

@*
@model UserModel

<h1>Главная</h1>
<div>
	@if (Model.FullName == null)
	{
		<a asp-area="User" asp-controller="Home" asp-action="Authorizate">Войти в профиль</a>
	}
	@if (Model.FullName != null)
	{
		<a asp-area="User" asp-controller="Home" asp-action="Index">@Model.FullName</a>
	}
	<a asp-area="User" asp-controller="Home" asp-action="Profile">Профиль</a>
	<a asp-area="User" asp-controller="Home" asp-action="Index">Лента</a>
	<a asp-area="User" asp-controller="Home" asp-action="Index">Задачи</a>
	<a asp-area="User" asp-controller="Home" asp-action="Index">Сообщество</a>
	<a asp-area="User" asp-controller="Home" asp-action="Index">ТОП-100 лидеров</a>
	@if (Model.FullName != null)
	{
		<a asp-area="User" asp-controller="Home" asp-action="LogoutUser">Выход</a>
	}
</div>
*@

<h1>Главная</h1>

CodeCareer/Areas/User/Views/Home/LogoutUser.cshtml
@{
	ViewBag.Title = "";
}
<h1>Вы вышли из профиля!</h1>
<a asp-area="User" asp-controller="Home" asp-action="Index">На главную</a>

CodeCareer/Areas/User/Views/Home/Profile.cshtml
@using CodeCareer.Areas.User.Services.Interfaces
@using CodeCareer.Areas.User.Services.Implementations.JsonServices
@model UserModel

@inject IPublicationService PublicationService

@{
	ViewBag.Title = "Профиль";
	var publications = PublicationService.GetPublicationModels().Where(p => p.User.Email == Model.Email).ToList();
	publications.Reverse();
}

<div>
	<div> @*Шапка*@

	</div>
	<a asp-area="User" asp-controller="Home" asp-action="EditProfile">Настроить профиль</a>
	<a asp-area="User" asp-controller="Home" asp-action="AddSkillTags">Добавить навыки</a>
	<h4>@Model.FullName - @Model.Status</h4>
	<p>@Model.Info</p>
	<p><a asp-area="User" asp-controller="Home" asp-action="ShowSubscribes" asp-route-userEmail="@Model.Email">@Model.Subscribers подписчиков</a></p>
	<p><a asp-area="User" asp-controller="Home" asp-action="ShowSubscriptions" asp-route-userEmail="@Model.Email">@Model.Subscriptions подписок</a></p>
	<p>@Model.Rating рейтинга</p>
</div>

<div>
	<h4>Навыки</h4>
	@foreach (var tag in Model.SkillTags)
	{
		@await Component.InvokeAsync("Tag", new {tagP = tag})
	}
</div>

<div>
	<a asp-area="User" asp-controller="Home" asp-action="CreatePublication">Создать публикацию</a>
</div>
<div>
	<h2>Публикации</h2>
	@foreach (var publication in publications)
	{
		@await Component.InvokeAsync("Publication", new { publicationP = publication })
	}
</div>

<a asp-area="User" asp-controller="Home" asp-action="AlienProfile" asp-route-userEmail="@Model.Email">Как мой профиль видят другие?</a>

CodeCareer/Areas/User/Views/Home/ShowSubscribes.cshtml
@using CodeCareer.Areas.User.Services.Interfaces
@using CodeCareer.Areas.User.Services.Implementations.JsonServices

@inject IUserService UserService

@model UserModel



@{
	var subscribers = UserService.GetUserModels().Where(u => Model.SubscribersEmails.Contains(u.Email));
}

<h1>Подписчики <a asp-area="User" asp-controller="Home" asp-action="AlienProfile" asp-route-userEmail="@Model.Email">@Model.FullName</a></h1>

<div>
	@foreach (var sub in subscribers)
	{
		<a asp-area="User" asp-controller="Home" asp-action="AlienProfile" asp-route-userEmail="@sub.Email">@sub.FullName</a>
	}
</div>

CodeCareer/Areas/User/Views/Home/ShowSubscriptions.cshtml
@using CodeCareer.Areas.User.Services.Interfaces
@using CodeCareer.Areas.User.Services.Implementations.JsonServices

@inject IUserService UserService

@model UserModel



@{
	var subscriptions = UserService.GetUserModels().Where(u => Model.SubscriptionsEmails.Contains(u.Email));
}

<h1>Подписки <a asp-area="User" asp-controller="Home" asp-action="AlienProfile" asp-route-userEmail="@Model.Email">@Model.FullName</a></h1>

<div>
	@foreach (var sub in subscriptions)
	{
		<div>
			<a asp-area="User" asp-controller="Home" asp-action="AlienProfile" asp-route-userEmail="@sub.Email">@sub.FullName</a>
		</div>
	}
</div>

CodeCareer/Areas/User/Views/Home/SuccessAuthorizate.cshtml
@model UserModel
<h1>Добро пожаловать, @Model.FullName</h1>

<a asp-area="User" asp-controller="Home" asp-action="Index">Перейти на сайт!</a>

CodeCareer/Areas/User/Views/Home/Top100Users.cshtml
@model List<UserModel>


<h1>Топ 100 пользователей</h1>
@for (int i = 0; i < Model.Count(); i++)
{
	<h3><a asp-area="User" asp-controller="Home" asp-action="AlienProfile" asp-route-userEmail="@Model[i].Email">@Model[i].FullName</a> - @Model[i].Rating рейтинга</h3>
}